[project]
name = "claude-code-demo"
version = "0.1.0"
description = "claude-code-demo"
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
pythonpath = ["."]
